//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WonderLab.Assets.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WonderLab.Assets.Language.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Saved Accounts 的本地化字符串。
        /// </summary>
        internal static string AC_Saved {
            get {
                return ResourceManager.GetString("AC_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All cores 的本地化字符串。
        /// </summary>
        internal static string Game_ALL {
            get {
                return ResourceManager.GetString("Game_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Game Cores 的本地化字符串。
        /// </summary>
        internal static string Game_Install {
            get {
                return ResourceManager.GetString("Game_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open logs window 的本地化字符串。
        /// </summary>
        internal static string Game_Log {
            get {
                return ResourceManager.GetString("Game_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open logs directory 的本地化字符串。
        /// </summary>
        internal static string Game_LogDir {
            get {
                return ResourceManager.GetString("Game_LogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Game Cores 的本地化字符串。
        /// </summary>
        internal static string Game_Manager {
            get {
                return ResourceManager.GetString("Game_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starred Cores 的本地化字符串。
        /// </summary>
        internal static string Game_Starred {
            get {
                return ResourceManager.GetString("Game_Starred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Game_Stop {
            get {
                return ResourceManager.GetString("Game_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        internal static string Home_Launch {
            get {
                return ResourceManager.GetString("Home_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Item_Add {
            get {
                return ResourceManager.GetString("Item_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string Item_Browse {
            get {
                return ResourceManager.GetString("Item_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full info 的本地化字符串。
        /// </summary>
        internal static string Item_Detail {
            get {
                return ResourceManager.GetString("Item_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Star 的本地化字符串。
        /// </summary>
        internal static string Item_Fav_Add {
            get {
                return ResourceManager.GetString("Item_Fav_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unstar 的本地化字符串。
        /// </summary>
        internal static string Item_Fav_Cancel {
            get {
                return ResourceManager.GetString("Item_Fav_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Item_Remove {
            get {
                return ResourceManager.GetString("Item_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Item_Search {
            get {
                return ResourceManager.GetString("Item_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string Launch_Notification {
            get {
                return ResourceManager.GetString("Launch_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        internal static string Main_Download {
            get {
                return ResourceManager.GetString("Main_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Main_Home {
            get {
                return ResourceManager.GetString("Main_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiplayer 的本地化字符串。
        /// </summary>
        internal static string Main_Multiplayer {
            get {
                return ResourceManager.GetString("Main_Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Nav_Settings_About {
            get {
                return ResourceManager.GetString("Nav_Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string Nav_Settings_Account {
            get {
                return ResourceManager.GetString("Nav_Settings_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        internal static string Nav_Settings_Appearance {
            get {
                return ResourceManager.GetString("Nav_Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game 的本地化字符串。
        /// </summary>
        internal static string Nav_Settings_Launch {
            get {
                return ResourceManager.GetString("Nav_Settings_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        internal static string Nav_Settings_Network {
            get {
                return ResourceManager.GetString("Nav_Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2021-2024 Blessing Studio 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Copyright {
            get {
                return ResourceManager.GetString("Settings_About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Our Team 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Developers {
            get {
                return ResourceManager.GetString("Settings_About_Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backend Team 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Developers_BE {
            get {
                return ResourceManager.GetString("Settings_About_Developers_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design Team 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Developers_DT {
            get {
                return ResourceManager.GetString("Settings_About_Developers_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frontend Team 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Developers_FE {
            get {
                return ResourceManager.GetString("Settings_About_Developers_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality Control Team 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Developers_QC {
            get {
                return ResourceManager.GetString("Settings_About_Developers_QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Donate {
            get {
                return ResourceManager.GetString("Settings_About_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon library references 的本地化字符串。
        /// </summary>
        internal static string Settings_About_IncludedIconLib {
            get {
                return ResourceManager.GetString("Settings_About_IncludedIconLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Source Library References 的本地化字符串。
        /// </summary>
        internal static string Settings_About_IncludedOSLib {
            get {
                return ResourceManager.GetString("Settings_About_IncludedOSLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Credits 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Thanks {
            get {
                return ResourceManager.GetString("Settings_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server support 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Thanks_ServerSupport {
            get {
                return ResourceManager.GetString("Settings_About_Thanks_ServerSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Technical support 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Thanks_TechSupport {
            get {
                return ResourceManager.GetString("Settings_About_Thanks_TechSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Version {
            get {
                return ResourceManager.GetString("Settings_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new account 的本地化字符串。
        /// </summary>
        internal static string Settings_Account_Add_Description {
            get {
                return ResourceManager.GetString("Settings_Account_Add_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Account_Title {
            get {
                return ResourceManager.GetString("Settings_Account_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme Color 的本地化字符串。
        /// </summary>
        internal static string Settings_Appearance_Color {
            get {
                return ResourceManager.GetString("Settings_Appearance_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamical color 的本地化字符串。
        /// </summary>
        internal static string Settings_Appearance_Monet {
            get {
                return ResourceManager.GetString("Settings_Appearance_Monet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string Settings_Appearance_Theme {
            get {
                return ResourceManager.GetString("Settings_Appearance_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Appearance_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Picture Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Background_Image {
            get {
                return ResourceManager.GetString("Settings_Background_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change picture 的本地化字符串。
        /// </summary>
        internal static string Settings_Background_ImageChange {
            get {
                return ResourceManager.GetString("Settings_Background_ImageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background rendering mode 的本地化字符串。
        /// </summary>
        internal static string Settings_Background_Mode {
            get {
                return ResourceManager.GetString("Settings_Background_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image used 的本地化字符串。
        /// </summary>
        internal static string Settings_Background_This {
            get {
                return ResourceManager.GetString("Settings_Background_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug Mode Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_DebugMode {
            get {
                return ResourceManager.GetString("Settings_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug mode 的本地化字符串。
        /// </summary>
        internal static string Settings_DebugMode_Change {
            get {
                return ResourceManager.GetString("Settings_DebugMode_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select language 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_Change {
            get {
                return ResourceManager.GetString("Settings_Language_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  .minecraft Folder Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Folder {
            get {
                return ResourceManager.GetString("Settings_Launch_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import .minecraft folder 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Folder_Add {
            get {
                return ResourceManager.GetString("Settings_Launch_Folder_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove this folder from list 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Folder_Remove {
            get {
                return ResourceManager.GetString("Settings_Launch_Folder_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select folder 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Folder_Select {
            get {
                return ResourceManager.GetString("Settings_Launch_Folder_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full screen 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_FullScreen {
            get {
                return ResourceManager.GetString("Settings_Launch_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Game {
            get {
                return ResourceManager.GetString("Settings_Launch_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game memory allocate 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Game_Memory {
            get {
                return ResourceManager.GetString("Settings_Launch_Game_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto allocate suitable memory 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Game_MemoryAuto {
            get {
                return ResourceManager.GetString("Settings_Launch_Game_MemoryAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game direcotories isolated 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Independent {
            get {
                return ResourceManager.GetString("Settings_Launch_Independent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Java {
            get {
                return ResourceManager.GetString("Settings_Launch_Java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Java path 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Java_Add {
            get {
                return ResourceManager.GetString("Settings_Launch_Java_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove this Java path from list 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Java_Remove {
            get {
                return ResourceManager.GetString("Settings_Launch_Java_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Java path 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Java_Select {
            get {
                return ResourceManager.GetString("Settings_Launch_Java_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto select suitable Java 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Java_SelectAuto {
            get {
                return ResourceManager.GetString("Settings_Launch_Java_SelectAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Launch_Title {
            get {
                return ResourceManager.GetString("Settings_Launch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jump to OOBE 的本地化字符串。
        /// </summary>
        internal static string Settings_OOBE {
            get {
                return ResourceManager.GetString("Settings_OOBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running {0} task 的本地化字符串。
        /// </summary>
        internal static string Task_ActiveInfo {
            get {
                return ResourceManager.GetString("Task_ActiveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is nothing to do ;) 的本地化字符串。
        /// </summary>
        internal static string Task_Info_Nothing {
            get {
                return ResourceManager.GetString("Task_Info_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Manager 的本地化字符串。
        /// </summary>
        internal static string Task_Manager {
            get {
                return ResourceManager.GetString("Task_Manager", resourceCulture);
            }
        }
    }
}
